openapi: 3.0.0
info:
  version: 1.0.0
  title: Read Worth API
servers:
  - url: "http://localhost:8000/"
paths:
  /api/{clientId}/me:
    get:
      summary: 自分の情報
      parameters:
        - in: path
          name: clientId
          schema:
            type: integer
          required: true
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        "403":
          description: "指定された組織にユーザーがいない場合"

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: number
          example: 1
        clientId:
          type: number
          example: 1
        name:
          type: string
          example: 工藤
        email:
          type: string
          example: tetetest@gmail.com
        apiToken:
            type: string
            example: xtGq57ENtxfHL7MB63jRoEhPM5d7Bah2rXRpUGowAuXsE2lzlM8DvnqH163T
        role:
          type: array
          items:
            type: object
            properties:
              isAccountManager:
                type: boolean
                example: true
              isBookManager:
                type: boolean
                example: true
              isClientManager:
                type: boolean
                example: true
