openapi: 3.0.0
info:
  version: 1.0.0
  title: Read Worth API
servers:
  - url: "http://localhost:8000/"
paths:
  /api/{clientId}/me:
    get:
      summary: 自分の情報
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: number
        clientId:
          type: number
        name:
          type: string
        email:
          type: string
        apiToken:
            type: string
        role:
          type: array
          properties:
            isAccountManager:
              type: boolean
            isBookManager:
              type: boolean
            isClientManager:
              type: boolean
