version: "3"

services:
  app:
    container_name: read_worth_app
    image: read_worth_backend
    command: /opt/app/docker/start-webapp.sh
    ports:
      - "8000:8000"
    volumes:
      - ./src/docker/php/app-dev.ini:/etc/php/8.1/mods-available/app.ini:ro
      - ./src:/opt/app

  db:
    container_name: read_worth_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: read_worth
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/docker/db/data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    ports:
      - "3307:3306"

  swagger-editor:
    container_name: read_worth_swagger_editor
    image: swaggerapi/swagger-editor
    ports:
      - "8001:8080"
    volumes:
      - ./api_oas_v3.yaml:/opt/api_oas_v3.yaml
    environment:
      SWAGGER_FILE: /opt/api_oas_v3.yaml

#  mailhog:
#    container_name: read_worth_mailhog
#    image: mailhog/mailhog
#    ports:
#      - target: 8025
#        published: 8025
#        protocol: tcp
#        mode: host

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'api-readworth.info-> http://app:8000'
#      STAGE: 'production'
#      FORCE_RENEW: 'true'
